### ISSUE TITLE
SC Parameter Types and Gas Pricing

### ISSUE THREAD

**Issue by mrtpain** [stratisproject/Documentation#31]
Looking for the content that used to represent how to format parameters when making contract calls via FN API. While looking for this content I also noticed I can no longer find the breakdown of Gas prices for different contract methods and operations.

Basically looking for these in Stratis academy. 
```
parameterTypes: Parameter[] = [
    new Parameter(1, 'Bool'),
    new Parameter(2, 'Byte'),
    new Parameter(3, 'Char'),
    new Parameter(4, 'String'),
    new Parameter(5, 'UInt'),
    new Parameter(6, 'Int'),
    new Parameter(7, 'ULong'),
    new Parameter(8, 'Long'),
    new Parameter(9, 'Address'),
    new Parameter(10, 'Byte Array')
  ];
```

**Comment by StratisIain** [comment]
Hey @mrtpain 

Is this what you're looking for?

[Param Type Serialization](https://academy.stratisplatform.com/Architecture%20Reference/SmartContracts/working-with-contracts.html#id3)

**Comment by mrtpain** [comment]
@StratisIain Ahh yeah thats what I was looking for. Was looking in the wrong spot in Developer Resources and trying to search. 

Thanks you can close this.
