### ISSUE TITLE
Update Gas Limit Maximum

### ISSUE THREAD

**Issue by mrtpain** [stratisproject/Documentation#34]
From 100,000 to 250,000.

From here:

https://github.com/stratisproject/StratisFullNode/blob/master/src/Stratis.Bitcoin.Features.SmartContracts/ReflectionExecutor/Consensus/Rules/SmartContractFormatLogic.cs#L14

Referenced here:

https://academy.stratisplatform.com/Architecture%20Reference/SmartContracts/appendix-gas-prices.html

**Comment by StratisIain** [comment]
Thanks @mrtpain !

Changes made here: [https://github.com/stratisproject/Documentation/commit/635894dc21f85c3ea370ac11fa05b234f29d559a](https://github.com/stratisproject/Documentation/commit/635894dc21f85c3ea370ac11fa05b234f29d559a
)
